# Generated by Django 3.2.7 on 2021-09-28 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0003_auto_20210922_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 11, 1, 26, 135746, tzinfo=utc)),
        ),
    ]
